name: PEDevsEssentials
version: 1.0
api:
- 3.0.0
- 3.0.1
- 3.0.0-ALPHA12
- 3.0.4
main: PEDevs\BaseAPI
author: PEDevs
website: https://github.com/PEDevs

permissions:
    essentials.heal.commands:
        default: op
    essentials.feed.commands:
        default: op
    essentials.spawn.commands:
        deault: true
    essentials.fly.commands:
        default: op
    essentials.warn.commands:
        default: op
    essentials.repair.commands:
        default: op
    essentials.tpa.commands:
        default: true
    essentials.tpak.commands:
        default: true
    essentials.tpar.commands:
        default: true
    essentials.broadcast.commands:
        default: op
