name: PEDevsEssentials
version: 1.0
api: [3.0.0]
main: PEDevs\MainBase
author: PEDevs
website: https://github.com/PEDevs

permissions:
    essentials.heal.commands:
        default: op
    essentials.feed.commands:
        default: op
    essentials.spawn.commands:
        deault: true
    essentials.fly.commands:
        default: op
    essentials.warn.commands:
        default: op
    essentials.repair.commands:
        default: op